const MESSAGE_TYPES = {
  ME: 'ME',
  LOCAL_USER: 'LOCAL_USER',
  USER_IN_LOCATION: 'USER_IN_LOCATION',
  NOT_YET_IN_LOCATION_USER: 'NOT_YET_IN_LOCATION_USER',
  NONE: 'NONE',
};

module.exports = { MESSAGE_TYPES };